/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    A: typeof import('./../components/a.vue')['default']
    Empty: typeof import('./../../../../common/components/Empty.vue')['default']
    InnerComponents: typeof import('./../components/innerComponents.vue')['default']
    MProgress: typeof import('./../../../../common/components/MProgress.vue')['default']
    OuterComponents: typeof import('./../../../../common/components/outerComponents.vue')['default']
    Picture: typeof import('./../../../../common/components/Picture.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SVGAPlayer: typeof import('./../../../../common/components/SVGAPlayer.vue')['default']
    VanButton: typeof import('vant/es')['Button']
  }
}
