/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActiveHeader: typeof import('./../../../../common/components/ActiveHeader.vue')['default']
    AvatarIcon: typeof import('./../../../../common/components/AvatarIcon.vue')['default']
    BoxCustomBg: typeof import('./../../../../common/components/BoxCustomBg.vue')['default']
    Calendar: typeof import('./../components/Calendar.vue')['default']
    CommonBtn: typeof import('./../../../../common/components/CommonBtn.vue')['default']
    ContentBox: typeof import('./../components/ContentBox.vue')['default']
    CustomTab: typeof import('./../components/CustomTab.vue')['default']
    Empty: typeof import('./../../../../common/components/Empty.vue')['default']
    Gift: typeof import('./../components/Gift.vue')['default']
    InputNumber: typeof import('./../components/InputNumber.vue')['default']
    LinearText: typeof import('./../components/LinearText.vue')['default']
    MProgress: typeof import('./../../../../common/components/MProgress.vue')['default']
    Page1: typeof import('./../components/Page1.vue')['default']
    Page2: typeof import('./../components/Page2.vue')['default']
    Picture: typeof import('./../../../../common/components/Picture.vue')['default']
    PopupBuyConfirm: typeof import('./../components/popup/PopupBuyConfirm.vue')['default']
    PopupBuyRecord: typeof import('./../components/popup/PopupBuyRecord.vue')['default']
    PopupCommon: typeof import('./../components/popup/PopupCommon.vue')['default']
    PopupConfirm: typeof import('./../components/popup/PopupConfirm.vue')['default']
    PopupExchangeRecord: typeof import('./../components/popup/PopupExchangeRecord.vue')['default']
    PopupExchangeRule: typeof import('./../components/popup/PopupExchangeRule.vue')['default']
    PopupExclusive: typeof import('./../components/popup/PopupExclusive.vue')['default']
    PopupScoreQues: typeof import('./../components/popup/PopupScoreQues.vue')['default']
    PopupSign: typeof import('./../components/popup/PopupSign.vue')['default']
    PopupVote: typeof import('./../components/popup/PopupVote.vue')['default']
    PopupVoteQues: typeof import('./../components/popup/PopupVoteQues.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTab: typeof import('./../components/ScrollTab.vue')['default']
    SortNum: typeof import('./../components/SortNum.vue')['default']
    SVGAPlayer: typeof import('./../../../../common/components/SVGAPlayer.vue')['default']
    UserCard: typeof import('./../components/UserCard.vue')['default']
    VanCountDown: typeof import('vant/es')['CountDown']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanStepper: typeof import('vant/es')['Stepper']
    VoteItem: typeof import('./../components/VoteItem.vue')['default']
  }
}
